"""Middleware behavior: request-ID headers on every response (including 404s)
and webhook body-size enforcement (411 / 400 / 413).

Header behavior is exercised through the real app; body-limit behavior is
unit-tested against the middleware directly because TestClient always sends a
Content-Length header, which is the normal case the check lets through."""

import os
import sys

import pytest
from fastapi.testclient import TestClient
from pydantic import SecretStr
from starlette.requests import Request
from starlette.responses import JSONResponse

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import agent.rate_limit as rate_limit_module
from agent.config import settings


@pytest.fixture
def client(tmp_path, monkeypatch):
    monkeypatch.setenv("GOOGLE_API_KEY", "dummy-key-for-tests")
    monkeypatch.setenv("TENANT_NAME", "test")
    settings.GOOGLE_API_KEY = SecretStr("dummy-key-for-tests")
    settings.DB_PATH = str(tmp_path / "test_middleware.db")
    from agent.storage import store as _store

    _store.db_path = settings.DB_PATH
    settings.REQUIRE_API_KEY = True
    settings.API_KEY = SecretStr("test-key-123")
    settings.RATE_LIMIT_PER_MINUTE = 100
    rate_limit_module._request_log.clear()

    import importlib

    import api.customer_support as cs_module
    import api.main as main_module

    importlib.reload(cs_module)
    importlib.reload(main_module)

    with TestClient(main_module.app, raise_server_exceptions=False) as c:
        yield c


AUTH = {"X-API-Key": "test-key-123"}


def test_request_id_and_version_headers_on_success(client):
    r = client.get("/health")
    assert r.status_code == 200
    assert r.headers.get("X-Request-ID")
    assert r.headers.get("X-API-Version") == "2.0.0"


def test_request_id_header_present_on_404(client):
    """404s are generated by the router — the middleware must still tag them."""
    r = client.get("/support/no-such-endpoint", headers=AUTH)
    assert r.status_code == 404
    assert r.headers.get("X-Request-ID")


def test_client_supplied_request_id_is_echoed(client):
    r = client.get("/health", headers={"X-Request-ID": "trace-abc-123"})
    assert r.headers.get("X-Request-ID") == "trace-abc-123"


# ── Webhook body limits ────────────────────────────────────────


def _webhook_request(path="/support/webhooks/inbound", headers=()):
    scope = {
        "type": "http",
        "http_version": "1.1",
        "method": "POST",
        "scheme": "http",
        "path": path,
        "raw_path": path.encode(),
        "query_string": b"",
        "headers": [(k.lower().encode(), v.encode()) for k, v in headers],
        "client": ("127.0.0.1", 12345),
        "server": ("testserver", 80),
    }
    return Request(scope)


async def _passthrough(request: Request) -> JSONResponse:
    return JSONResponse({"ok": True})


async def test_webhook_without_content_length_gets_411():
    from api.middleware import WebhookBodyLimitMiddleware

    mw = WebhookBodyLimitMiddleware(app=None)
    resp = await mw.dispatch(_webhook_request(), _passthrough)
    assert resp.status_code == 411
    assert b"LENGTH_REQUIRED" in resp.body


async def test_webhook_with_non_integer_content_length_gets_400():
    from api.middleware import WebhookBodyLimitMiddleware

    mw = WebhookBodyLimitMiddleware(app=None)
    resp = await mw.dispatch(_webhook_request(headers=[("Content-Length", "abc")]), _passthrough)
    assert resp.status_code == 400
    assert b"INVALID_CONTENT_LENGTH" in resp.body


async def test_oversized_webhook_gets_413():
    from api.middleware import WebhookBodyLimitMiddleware

    mw = WebhookBodyLimitMiddleware(app=None)
    resp = await mw.dispatch(
        _webhook_request(headers=[("Content-Length", str(1024 * 1024 + 1))]),
        _passthrough,
    )
    assert resp.status_code == 413
    assert b"PAYLOAD_TOO_LARGE" in resp.body


async def test_webhook_within_limit_passes_through():
    from api.middleware import WebhookBodyLimitMiddleware

    mw = WebhookBodyLimitMiddleware(app=None)
    resp = await mw.dispatch(_webhook_request(headers=[("Content-Length", "512")]), _passthrough)
    assert resp.status_code == 200


async def test_non_webhook_path_skips_content_length_check():
    from api.middleware import WebhookBodyLimitMiddleware

    mw = WebhookBodyLimitMiddleware(app=None)
    resp = await mw.dispatch(_webhook_request(path="/chat/sessions"), _passthrough)
    assert resp.status_code == 200
